/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author fekabatman
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        patientField = new javax.swing.JTextField();
        DoctorField = new javax.swing.JTextField();
        StartBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nextPatientTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        prevDoctorTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        prevPatientTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        nextDoctorTable = new javax.swing.JTable();
        StatusLabel = new javax.swing.JLabel();
        GenerateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(812, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Végeredmény");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 190, 30));

        jLabel2.setText("Előzetes Állapot");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 190, 30));
        jPanel1.add(patientField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 140, 30));
        jPanel1.add(DoctorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 140, 30));

        StartBtn.setText("Start");
        jPanel1.add(StartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 130, 30));

        jLabel3.setText("Orvosok száma:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        jLabel4.setText("Páciensek száma:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 90, 30));

        nextPatientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Név", "Állapot", "Korl"
            }
        ));
        jScrollPane1.setViewportView(nextPatientTable);
        if (nextPatientTable.getColumnModel().getColumnCount() > 0) {
            nextPatientTable.getColumnModel().getColumn(2).setPreferredWidth(35);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 190, 310));

        prevDoctorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Név", "Szakterület"
            }
        ));
        prevDoctorTable.setCellSelectionEnabled(true);
        jScrollPane2.setViewportView(prevDoctorTable);
        prevDoctorTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 190, 310));

        prevPatientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Név", "Állapot", "Kor"
            }
        ));
        jScrollPane3.setViewportView(prevPatientTable);
        if (prevPatientTable.getColumnModel().getColumnCount() > 0) {
            prevPatientTable.getColumnModel().getColumn(2).setPreferredWidth(35);
        }

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 190, 310));

        nextDoctorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Név", "Szakterület"
            }
        ));
        jScrollPane4.setViewportView(nextDoctorTable);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 190, 310));
        jPanel1.add(StatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 210, -1));

        GenerateBtn.setText("Generál");
        jPanel1.add(GenerateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 130, 30));

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DoctorField;
    private javax.swing.JButton GenerateBtn;
    private javax.swing.JButton StartBtn;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable nextDoctorTable;
    private javax.swing.JTable nextPatientTable;
    private javax.swing.JTextField patientField;
    private javax.swing.JTable prevDoctorTable;
    private javax.swing.JTable prevPatientTable;
    // End of variables declaration//GEN-END:variables

    public JTextField getDoctorField() {
        return DoctorField;
    }

    public void setDoctorField(JTextField DoctorField) {
        this.DoctorField = DoctorField;
    }

    public JButton getGenerateBtn() {
        return GenerateBtn;
    }

    public void setGenerateBtn(JButton GenerateBtn) {
        this.GenerateBtn = GenerateBtn;
    }

    public JButton getStartBtn() {
        return StartBtn;
    }

    public void setStartBtn(JButton StartBtn) {
        this.StartBtn = StartBtn;
    }

    public JLabel getStatusLabel() {
        return StatusLabel;
    }

    public void setStatusLabel(JLabel StatusLabel) {
        this.StatusLabel = StatusLabel;
    }


    public JTable getNextDoctorTable() {
        return nextDoctorTable;
    }

    public void setNextDoctorTable(JTable nextDoctorTable) {
        this.nextDoctorTable = nextDoctorTable;
    }

    public JTable getNextPatientTable() {
        return nextPatientTable;
    }

    public void setNextPatientTable(JTable nextPatientTable) {
        this.nextPatientTable = nextPatientTable;
    }

    public JTextField getPatientField() {
        return patientField;
    }

    public void setPatientField(JTextField patientField) {
        this.patientField = patientField;
    }

    public JTable getPrevDoctorTable() {
        return prevDoctorTable;
    }

    public void setPrevDoctorTable(JTable prevDoctorTable) {
        this.prevDoctorTable = prevDoctorTable;
    }

    public JTable getPrevPatientTable() {
        return prevPatientTable;
    }

    public void setPrevPatientTable(JTable prevPatientTable) {
        this.prevPatientTable = prevPatientTable;
    }

   
}
